[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/amoghe/distillog"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1.0"

[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"
  version = "1.3.3"

[[constraint]]
  name = "github.com/bxcodec/faker"
  version = "2.0.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
