basePath: /
host: localhost:5000
info:
  contact:
    email: nexters@kakao.com
    name: API Support
    url: http://localhost:5000
  description: todolist API
  title: todolist API
  version: 21.0.0
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
